name: Gitub Actions test
  
on: 
      pull_request:
        branches: [master]
jobs: 
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
         go-version: '1.16.1' # The Go version to download (if necessary) and use.
      - name: Run build
        run: go build .
      - name: Run vet & lint
        run: |
         go vet .
         golint .  
      - run: go run ./3/main.go
